services:
  - type: web
    name: streamlit-app
    env: docker
    plan: free
    repo: https://github.com/soukainafarisse16/streamlit-app.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
